// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V11_0_0_55666.UpdateFields.V11_2_7_64632
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class DelveData : IDelveData
    {
        public int MapID { get; set; }
        public ulong InstanceID { get; set; }
        public int Field_10 { get; set; }
        public int SpellID { get; set; }
        public WowGuid[] PlayersEligibleForRewards { get; set; }
        public uint RestrictingRewardPlayers { get; set; }
    }
}

